include /home/kristyan/.cache/kdwm/theme/kitty-colors.conf
font_family JetBrains Mono
font_size 11.0
background_opacity 0.90
dynamic_background_opacity yes
window_padding_width 10
confirm_os_window_close 0
enable_audio_bell no
